### ISSUE TITLE
Add comments to see translation in IDE

### ISSUE THREAD

**Issue by ikbendewilliam** [icapps/flutter-icapps-translations#31]
I18n adds the default translation in file as description, this has the effect that in your IDE you can immediately see what it means and prevents wrong labels.

```
  /// No description provided for @careerInfoTitle.
  ///
  /// In en, this message translates to:
  /// **'Info'**
  String get careerInfoTitle;
```

![image](https://user-images.githubusercontent.com/20164321/112693101-4f295900-8e80-11eb-9a2f-3d09ccdffa2a.png)

**Comment by vanlooverenkoen** [comment]
Ooooh that is indeed a very nice feature.

**Comment by vanlooverenkoen** [comment]
This should be implemented in locale_gen first because everything related to generating code in done there. I will create a new ticket for locale_gen
